export const CODES = {
'1K':"kilo",
'1/4K2':"cuarto",
'1/4K3':"cuarto",
'1/2K4':"medio",
'1/2K5':"medio",
'3/4K6':"cuarto",
'3/4K6,50':"cuarto",
'Cucu*1':"cucu-1",
'Granita1/4':"granita-cuarto",
'Granita1/2':"granita-medio",
'P. Alm. Chico':"alm-chico",
'P. Alm. Gde.':"alm-gde",
'Cucu*2':"cucu-1",
'Vasos*1':"tacitas",
'Vasos*2':"tacitas",
'RgCucureg':"cucu-reg",
'RgVasosreg':"tacita-reg",
'ojo':"ojo",
'P.Torta C.C.':"cheese-cake",
'lista':"lista",
'iman':"iman",
'Copasundae':"copa-helada",
'mas':"mas",
'menos':"menos",
'Cuch':"cucu-1",
'nvo':"nvo",
'BanSplit':"copa-split",
'Copa Fresa':"copa-fresa",
'Granita 1':"",
'p. alm':"",

}